### ISSUE TITLE
Support for reactstrap or third party react elements

### ISSUE THREAD

**Issue by snics** [anantoghosh/gatsby-plugin-purgecss#221]
**What's the problem?**
I also use [reactstrap](https://reactstrap.github.io/) with Gatsbyjs and your plugin and would like to continue using it. Unfortunately the CSS classes are removed from [reactstrap](https://reactstrap.github.io/). Give you a solution or can you add a feature that takes third party react elements into account?

**Describe the solution you'd like**
An automatic detection of CSS that detects third party react elements or a feature like `tailwind: true`

**Comment by anantoghosh** [comment]
You are facing the issue https://github.com/anantoghosh/gatsby-plugin-purgecss#issue-5-using-npm-packages-with-components-which-import-css-files
Try the solution mentioned.

There still be the issue that it won't be optimally purged because it would consider all the components as   being used. For that you could add only the components which you use to the content option.

**Comment by snics** [comment]
Okay, for me it is enough that there are not so many stylings that are removed. Thanks for your help!
